city_list = [
# "Tirana Albania",
# "Kabul Afghanistan",
# "Alger Algeria"
# "Fagatogo American Samoa",
# "Andorra la Vella Andorra",
# "Luanda Angola",
# "The Valley Anguilla",
# "Saint John's Antigua and Barbuda",
# "Buenos Aires Argentina",
# "Yerevan Armenia",
# "Oranjestad Aruba",
# "Canberra Australia",
# "Wien Austria",
# "Baku Azerbaijan",
# "Nassau Bahamas",
# "al-Manama Bahrain",
# "Dhaka Bangladesh",
# "Bridgetown Barbados",
# "Minsk Belarus",
# "Bruxelles [Brussel] Belgium",
# "Belmopan Belize",
# "Porto-Novo Benin",
# "Hamilton Bermuda",
# "Thimphu Bhutan",
# "La Paz Bolivia",
# "Sarajevo Bosnia and Herzegovina",
# "Gaborone Botswana",
# "Brasília Brazil",
# "Bandar Seri Begawan Brunei",
# "Sofia Bulgaria",
# "Ouagadougou Burkina Faso",
# "Bujumbura Burundi",
# "Phnom Penh Cambodia",
# "Yaounde Cameroon",
# "Ottawa Canada",
# "Praia Cape Verde",
# "George Town Cayman Islands",
# "Bangui Central African Republic",
# "N'Djamena Chad",
# "Santiago de Chile Chile",
# "Peking China",
# "Flying Fish Cove Christmas Island",
# "West Island Cocos (Keeling) Islands",
# "Santaf Colombia",
# "Moroni Comoros",
# "Brazzaville Congo",
# "Avarua Cook Islands",
# "San José Costa Rica",
# "Zagreb Croatia",
# "La Habana Cuba",
# "Nicosia Cyprus",
# "Praha Czech Republic",
# "Copenhagen Denmark",
# "Djibouti Djibouti",
# "Roseau Dominica",
# "Santo Domingo de Guzm Dominican Republic",
# "Dili East Timor",
# "Quito Ecuador",
# "Cairo Egypt",
# "San Salvador El Salvador",
# "London England",
# "Malabo Equatorial Guinea",
# "Asmara Eritrea",
# "Tallinn Estonia",
# "Addis Abeba Ethiopia",
# "Stanley Falkland Islands",
# "Tórshavn Faroe Islands",
# "Suva Fiji Islands",
# "Helsinki [Helsingfors] Finland",
# "Paris France",
# "Cayenne French Guiana",
# "Papeete French Polynesia",
# "Libreville Gabon",
# "Banjul Gambia",
# "Tbilisi Georgia",
# "Berlin Germany",
# "Accra Ghana",
# "Gibraltar Gibraltar",
# "Athenai Greece",
# "Nuuk Greenland",
# "Saint George's Grenada",
# "Basse-Terre Guadeloupe",
# "Aga Guam",
# "Ciudad de Guatemala Guatemala",
# "Conakry Guinea",
# "Bissau Guinea-Bissau",
# "Georgetown Guyana",
# "Port-au-Prince Haiti",
# "Citt Holy See (Vatican City State)",
# "Tegucigalpa Honduras",
# "Victoria Hong Kong",
# "Budapest Hungary",
# "Reykjavík Iceland",
# "New Delhi India",
# "Jakarta Indonesia",
# "Tehran Iran",
# "Baghdad Iraq",
# "Dublin Ireland",
# "Jerusalem Israel",
# "Roma Italy",
# "Yamoussoukro Ivory Coast",
# "Kingston Jamaica",
# "Tokyo Japan",
# "Amman Jordan",
# "Astana Kazakhstan",
# "Nairobi Kenya",
# "Bairiki Kiribati",
# "Kuwait Kuwait",
# "Bishkek Kyrgyzstan",
# "Vientiane Laos",
# "Riga Latvia",
# "Beirut Lebanon",
# "Maseru Lesotho",
# "Monrovia Liberia",
# "Tripoli Libyan Arab Jamahiriya",
# "Vaduz Liechtenstein",
# "Vilnius Lithuania",
# "Luxembourg [Luxemburg/L Luxembourg",
# "Macao Macao",
# "Skopje North Macedonia",
# "Antananarivo Madagascar",
# "Lilongwe Malawi",
# "Kuala Lumpur Malaysia",
# "Male Maldives",
# "Bamako Mali",
# "Valletta Malta",
# "Dalap-Uliga-Darrit Marshall Islands",
# "Fort-de-France Martinique",
# "Nouakchott Mauritania",
# "Port-Louis Mauritius",
# "Mamoutzou Mayotte",
# "Ciudad de M Mexico",
# "Palikir Micronesia, Federated States of",
# "Chisinau Moldova",
# "Monaco-Ville Monaco",
# "Ulan Bator Mongolia",
# "Podgorica Montenegro",
# "Plymouth Montserrat",
# "Rabat Morocco",
# "Maputo Mozambique",
# "Rangoon (Yangon) Myanmar",
# "Windhoek Namibia",
# "Yaren Nauru",
# "Kathmandu Nepal",
# "Amsterdam Netherlands",
# "Willemstad Netherlands Antilles",
# "Noum New Caledonia",
# "Wellington New Zealand",
# "Managua Nicaragua",
# "Niamey Niger",
# "Abuja Nigeria",
# "Alofi Niue",
# "Kingston Norfolk Island",
# "Pyongyang North Korea",
# "Belfast Northern Ireland",
# "Garapan Northern Mariana Islands",
# "Oslo Norway",
# "Masqat Oman",
# "Islamabad Pakistan",
# "Koror Palau",
# "Gaza Palestine",
# "Ciudad de Panamá Panama",
# "Port Moresby Papua New Guinea",
# "Asunción Paraguay",
# "Lima Peru",
# "Manila Philippines",
# "Adamstown Pitcairn",
# "Warszawa Poland",
# "Lisboa Portugal",
# "San Juan Puerto Rico",
# "Doha Qatar",
# "Saint-Denis Reunion",
# "Bucuresti Romania",
# "Moscow Russian Federation",
# "Kigali Rwanda",
# "Jamestown Saint Helena",
# "Basseterre Saint Kitts and Nevis",
# "Castries Saint Lucia",
# "Saint-Pierre Saint Pierre and Miquelon",
# "Kingstown Saint Vincent and the Grenadines",
# "Apia Samoa",
# "San Marino San Marino",
# "São Tomé Sao Tome and Principe",
# "Riyadh Saudi Arabia",
# "Edinburgh Scotland",
# "Dakar Senegal",
# "Belgrade Serbia",
# "Victoria Seychelles",
# "Freetown Sierra Leone",
# "Singapore Singapore",
# "Bratislava Slovakia",
# "Ljubljana Slovenia",
# "Honiara Solomon Islands",
# "Mogadishu Somalia",
# "Pretoria South Africa",
# "Seoul South Korea",
# "Juba South Sudan",
# "Madrid Spain",
# "Colombo, Sri Jayawardenepura Kotte Sri Lanka",
# "Khartum Sudan",
# "Paramaribo Suriname",
# "Longyearbyen Svalbard and Jan Mayen",
# "Mbabane Swaziland",
# "Stockholm Sweden",
# "Bern Switzerland",
# "Damascus Syria",
# "Dushanbe Tajikistan",
# "Dodoma Tanzania",
# "Bangkok Thailand",
# "Kinshasa The Democratic Republic of Congo",
# "Lomé Togo",
# "Fakaofo Tokelau",
# "Nuku'alofa Tonga",
# "Port-of-Spain Trinidad and Tobago",
# "Tunis Tunisia",
# "Ankara Turkey",
# "Ashgabat Turkmenistan",
# "Cockburn Town Turks and Caicos Islands",
# "Funafuti Tuvalu",
# "Kampala Uganda",
# "Kyiv Ukraine",
# "Abu Dhabi United Arab Emirates",
# "London United Kingdom",
# "Washington United States",
# "Montevideo Uruguay",
# "Toskent Uzbekistan",
# "Port-Vila Vanuatu",
# "Caracas Venezuela",
# "Vetican City Vetican City",
# "Hanoi Vietnam",
# "Road Town Virgin Islands, British",
# "Charlotte Amalie Virgin Islands, U.S.",
# "Cardiff Wales",
# "Mata-Utu Wallis and Futuna",
# "El-Aai Western Sahara",
# "Sanaa Yemen",
# "Lusaka Zambia",
# "Harare Zimbabwe"
]
