# Generated by Django 3.2.12 on 2024-01-12 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hotel_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_id', models.BigIntegerField(unique=True)),
                ('hotel_name', models.CharField(max_length=250)),
                ('rating', models.CharField(max_length=250)),
                ('hotel_review', models.CharField(default='No review given', max_length=250)),
                ('hotel_description', models.CharField(default='No description given', max_length=250)),
                ('location', models.CharField(max_length=250)),
                ('city_and_country', models.CharField(max_length=250)),
                ('room_policy', models.CharField(default='No room policy given', max_length=250)),
                ('price_inc_tax', models.CharField(max_length=250)),
                ('hotel_url', models.TextField()),
            ],
        ),
    ]
