# Generated by Django 3.2.12 on 2024-01-12 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel_info',
            name='hotel_description',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='hotel_info',
            name='hotel_review',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='hotel_info',
            name='hotel_url',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='hotel_info',
            name='room_policy',
            field=models.CharField(max_length=250),
        ),
    ]
