# Generated by Django 3.2.12 on 2024-01-12 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_auto_20240112_0853'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel_info',
            old_name='hotel_description',
            new_name='price_incl_tax',
        ),
        migrations.RenameField(
            model_name='hotel_info',
            old_name='price_inc_tax',
            new_name='room_description',
        ),
    ]
